export const WEATHER_CONST_STRING = {
  GET_WEATHER_BY_CURRENT_LOCATION_REQUEST: 'GET_WEATHER_BY_CURRENT_LOCATION_REQUEST',
  GET_WEATHER_BY_CURRENT_LOCATION_SUCCESS: 'GET_WEATHER_BY_CURRENT_LOCATION_SUCCESS',
  GET_WEATHER_BY_CURRENT_LOCATION_FAILURE: 'GET_WEATHER_BY_CURRENT_LOCATION_FAILURE',
  SET_POSITION: 'SET_POSITION',
  GET_WEAHTER_BY_CITY_REQUEST: 'GET_WEAHTER_BY_CITY_REQUEST',
  GET_WEAHTER_BY_CITY_SUCCESS: 'GET_WEAHTER_BY_CITY_SUCCESS',
  GET_WEAHTER_BY_CITY_FAILURE: 'GET_WEAHTER_BY_CITY_FAILURE',
  
}

